site_name: Nexlayer Docs
site_url: https://docs.nexlayer.com

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: en
  palette:
   - scheme: slate #dark mode
     primary: custom
     accent: custom
     toggle:
       icon: material/toggle-switch
       name: Switch to dark mode
   
   - scheme: default #light mode
     primary: custom
     accent: custom
     toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - monorepo:
  
nav:
  - Docs:
    - Welcome: welcome.md
    - Introduction: 'index.md'
    - Quickstart: 'quickstart.md'
    - FAQ: 'get-started/faq.md'
    # - Introduction: get-started/introduction.md
    # - guides/agent-integration.md
    # - guides/ci.md
    # - guides/cli.md
    # - guides/examples.md
    # - guides/post-deploy.md
    # - guides/quickstart.md
    # - guides/web-ui.md



markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes

copyright: |
  &copy; 2025 <a href="https://github.com/Nexlayer/docs"  target="_blank" rel="noopener">Nexlayer</a>

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/js/all.min.js
  - js/nav-icons.js