site_name: Nexlayer Docs
site_url: https://docs.nexlayer.com
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: en
  palette:
  - scheme: slate
    primary: custom
    accent: custom
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - scheme: default
    primary: custom
    accent: custom
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  features:
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.tabs
  - navigation.sections
  - navigation.footer
  - navigation.indexes
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  - navigation.expand
  icon:
    repo: fontawesome/brands/github
plugins:
- search
- monorepo: null
nav:
- Docs:
  - Documentation: index.md
  - Get Started:
    - Introduction: get-started/introduction.md
    - FAQ: get-started/faq.md
  - Guides:
    - Quickstart: guides/quickstart.md
    - Agent Integration: guides/agent-integration.md
    - CI: guides/ci.md
    - Examples: guides/examples.md
    - Post Deploy: guides/post-deploy.md
    - Web UI: guides/web-ui.md
  - Deployment:
    - Readme: deployment/readme.md
- CLI: guides/cli.md
- API & SDK:
  - Code_of_conduct: api-reference/CODE_OF_CONDUCT.md
  - Notice: api-reference/NOTICE.md
  - Readme: api-reference/readme.md
  - Authentication: api-reference/docs/guides/authentication.md
  - Quickstart: api-reference/docs/guides/quickstart.md
  - Readme: api-reference/docs/api/readme.md
markdown_extensions:
- pymdownx.details
- pymdownx.superfences
- pymdownx.mark
- attr_list
- md_in_html
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.arithmatex:
    generic: true
- footnotes
copyright: '&copy; 2025 <a href="https://github.com/Nexlayer/docs"  target="_blank"
  rel="noopener">Nexlayer</a>

  '
extra_css:
- stylesheets/extra.css
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/js/all.min.js
- js/nav-icons.js
